apiVersion: apps/v1
kind: Deployment
metadata:
  name: node001
  labels:
    app: node001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node001
  template:
    metadata:
      labels:
        app: node001
    spec:
      hostname: node001
      containers:
      - name: node001
        image: minicla-node:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: shared-data
          mountPath: /tmp/shared-data
      volumes:
      - name: shared-data
        hostPath:
          path: /vagrant/shared-data
          type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: node001
spec:
  selector:
    app: node001
  ports:
  - name: slurmd
    port: 6818
    targetPort: 6818
  - name: ssh
    port: 22
    targetPort: 22
