version: '3.8'

services: 
  # The Admin/Management Node
  slurm-admin:
    image: minicla-admin:latest
    container_name: admin
    hostname: admin
    volumes:
      - ./shared-data:/tmp/shared-data
    networks:
      - slurm-net
    entrypoint: ["/app/admin.entrypoint.sh"]

  # Compute Node 1
  node001:
    image: minicla-node:latest
    container_name: node001
    hostname: node001
    volumes:
      - ./shared-data:/tmp/shared-data
    networks:
      - slurm-net
    # volumes:
    #   - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/app/node.entrypoint.sh"]

  # Compute Node 2
  node002:
    image: minicla-node:latest
    container_name: node002
    hostname: node002
    volumes:
      - ./shared-data:/tmp/shared-data
    networks:
      - slurm-net
    # volumes:
    #   - ./entrypoint.sh:/entrypoint.sh
    entrypoint: ["/app/node.entrypoint.sh"]

    
# volumes:
#   shared-data: # This defines the shared space accessible by all nodes

networks:
  slurm-net: # This enables the embedded Docker DNS!
